### ISSUE TITLE
Create AWSLambda node that evaluates nodes in the cloud

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#126]
**Description**
Create a node that wraps another node. This wrapped node is then excuted on an AWS lambda function

Also add a notebook showing an example use.

**Comment by dsully1992** [comment]
@mpu-creare Are you aware of anyone recently adding a dependency on `bs4`? The Lambda function appears to fail to import `podpac.core.pipeline.Pipeline` because of that? 

I'm updating the DockerFile to install bs4 now, but it's worth asking. The turnaround on updating and testing the Lambda is long, and if it's something podpac needs, it should go in the setup.py/requirements.txt to be installed by `pip install -e .[devall]`

**Comment by dsully1992** [comment]
I'm not sure what is going on with the podpac installation on the Lambda function. For some reason it fails now, and I can see that some of the dependencies in the `setup.py` aren't installed by the DockerFile. However, I haven't changed my imports in the handler, so I'm not sure why this is becoming an issue now. My attempt at a solution was to add those dependencies to requirements.txt, which includes them in the package.zip. However, this results in the zip being too large, which presents us with that problem again. @mpu-creare Can we take a look at this together? It seems like I'm missing a potentially easier solution.

**Comment by mpu-creare** [comment]
bs4 (beautifulsoup4) is not a new dependency... I don't think. It should have been under the datatype requirements for a while .

**Comment by dsully1992** [comment]
As we've discussed, these dependency problems were new to the Lambda because of how PODPAC's module structure. This has been addressed, allowing completion of this issue for the short term. I created a [pull request](!144) for this feature, and will create a couple new issues for future enhancements, such as installing other dependencies on the AWS Lambda function to allow all `Node` types to be evaluated, and unit testing the PODPAC `aws_lambda` wrapper.
