### ISSUE TITLE
Create a set of simple example notebooks

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#127]
**Description**
Create very short notebooks that show how to use basic datasource and algorithm nodes. 

TODO: Define and prioritize.

**Comment by mpu-creare** [comment]
Sofar I have the following notebooks that need to be created. These should be standalone and **short** (except for the first one), assume you have MATLAB user on your hands. We should use a consistent format as well in terms of introductory text and heading style:

* [ ] Getting Started (Introduction + Index)
* [x] Reading a raster file
* [ ] Reading a .csv file
* [ ] Creating coordinates
* [ ] Retrieving SMAP data
* [ ] Combining data sources in a custom algorithm
* [ ] Running pipelines in the cloud (using AWS Lambda functions)
* [ ] Compositing data sources together
* [ ] Looking at SMAP-Sentinal data

**Comment by jmilloy** [comment]
- [ ] Writing pipelines
 - [ ] Sharing nodes (outputting a node's pipeline definition)
 - [ ] Using custom nodes in pipelines (plugins)
 - [ ] Advanced coordinates creation (e.g. using ArrayCoordinates1d, etc directly in order to specify different ctypes for different dimensions)
 - [ ] Coordinates usage (methods and properties API)

What do you think about some additional pipeline notebooks? I guess it would only really make sense if there are other non-AWS uses at this point for pipelines. In particular, there might not be a use-case for pipeline plugins at this point, I could see postponing that one. Or possibly these should all be in one notebook -- I don't have a good sense of how short "short" is.

Same for coordinates... should I just include all three topics in one notebook, or the separation worthwhile?

**Comment by jmilloy** [comment]
Plotting outputs and/or using xarray?
