### ISSUE TITLE
 Fix up traitlets usage in pipeline node

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#141]
**Description**
There are a couple of issues in the pipeline node. 

* Generally you shouldn't set any attributes in traitlets validators
* When you create a pipeline with anything but the json the `hash` returns 0 (not correct)

**Comment by dsully1992** [comment]
Note: this caused some pains in creating a `pipeline` in our Lambda function. I've worked around that by converting the definition (`OrderedDict`) to JSON, and instantiation the pipeline with that instead. However, it seems a slight optimization to update `handler.py` to use the definition once this issue is resolved.
