### ISSUE TITLE
QUESTION: hasattr vs util.trait_is_defined()

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#160]
**Description**

Looking at the Compositor, it looks like you use the built in `hasattr` instead of looking at the objects _trait_values.  The `util` method `trait_is_defined()` uses `_trait_values`.

Do you have any guidance as to when to use one vs the other?   DOes `hasattr` make a call to the traitlets default if it accesses the member?

**Comment by mpu-creare** [comment]
> Do you have any guidance as to when to use one vs the other? DOes hasattr make a call to the traitlets default if it accesses the member? 

That's the one! It might be that the compositor is out-dated.

**Comment by jmilloy** [comment]
The compositor code is definitely out-dated.

 - It looks like `hasattr` causes a call to the traitlets default if the trait hasn't been set yet, so I guess you have to avoid `hasattr` if you don't want to call the default method.
 - But `_trait_values` won't contain a key for the trait if it hasn't been set yet, so that's not a suitable alternative if you want to know if an object has the attribute. You can't use `_trait_values` to replace `hasattr`.
 - However, possibly `has_trait` is better than `hasattr` because it will return True without running the default method.
 - On the other hand, `has_trait` (and checking `_trait_values`) will return False if the attribute exists but is not a trait! That's distinctly possible, say if someone subclasses DataSource and sets the native_coordinates directly in the class definition. Maybe if they do that it's their own fault, or maybe `obj.has_trait(trait) or hasattr(obj, trait)` would is the most general it wouldn't call the traitlets default method but falls back on checking hasattr if necessary.

The Compositor uses hasattr to propagate the interpolation attribute to sources. I think we could use `has_trait` or the `has_trait or hasattr` combo for this one. I think it would be better to check if the source is a DataSource or Compositor because those two types of nodes always have an interpolation trait and the others (Pipeline and Algoritthm) do not.

The Compositor also uses hasattr to set native_coordinates in a way that I don't understand at a first glance. I think that is probably incorrect and needs a closer look than just changing `hasattr`.

Lastly, `None` is a sometimes a valid trait value. So I think `trait_is_defined` is implemented incorrectly. I think it should be simply `return obj.has_trait(trait) and trait in obj._trait_values` (without the try-except, too). If you need to also check for None in a specific case, then you should do `if trait_is_defined(obj, trait) and getattr(obj, trait) is not None`.

**Comment by mlshapiro** [comment]
> Lastly, `None` is a sometimes a valid trait value. So I think `trait_is_defined` is implemented incorrectly. I think it should be simply `return obj.has_trait(trait) and trait in obj._trait_values` (without the try-except, too). If you need to also check for None in a specific case, then you should do `if trait_is_defined(obj, trait) and getattr(obj, trait) is not None`.

Ah yes - we should handle this and leave off the "none" case.

when you call `obj.has_trait` it will try to run the default, so we shouldn't do that. I think we could probably just leave it as:

```
    try:
        val = obj._trait_values[trait]
        return True
    except (KeyError, RuntimeError, tl.TraitError):
        return False
```

**Comment by jmilloy** [comment]
But, really, why can't you just do `return trait in obj._trait_values`? What does the RuntimeError and tl.TraitError catch?

**Comment by mlshapiro** [comment]
Catches bad programming :)  you are totally right. I'll fix.

has_trait works great, don't know how i missed that.
