### ISSUE TITLE
Generalize S3 Handling from GFS/TerrainTiles

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#194]
**Description**

We have two examples of how to integrate data from an S3 Bucket (GFS, TerrainTiles).
We should determine if there any pieces that are abstractable and/or worth abstracting.
Then we should figure out the best way to include this with an arbitrary DataSource node.
It could be a decorator on the DataSource, or perhaps a keyword, not sure what will work best.

- It should be very easy for a user to switch between a local filepath and an s3 filepath.
- It should have a simple way to download the s3 file to a local path

**Sample Code**

Decorator

```python
@S3(bucket='my-bucket', key='asdf', secret='asdf')
class MyDataSource(Rasterio):
   source = 'geo/file.tiff'
```

Keyword

```python
class MyDataSource(Rasterio):
   source = 'geo/file.tiff'
   s3 = {
      'bucket': 'my-bucket',
      'key':'asdf', 
      'secret': 'asdf'
    }
```

**Comment by jmilloy** [comment]
Loading a local GFS file is just an unmodified Rasterio node: `gfs_source = Rasterio(source=filename)`, and loading the aggregated data from a directory should be a thinly wrapped Compositor, once that is implemented properly. I don't think there is really any shared code between the S3 GFS and a local GFS. They are both thin wrappers, and the local GFS wrapper depends completely on your local file structure.

I think it would make sense to specifically generalize the `Rasterio` node to accept an S3 source (in addition to a file path or BytesIO as it does now). That would make our S3 data sources very thin or ideally we wouldn't need subclasses at all.

Maybe the use-case you are thinking about is S3 data that you have downloaded with a file structure that mimics the key names. If that's what we want to support, I would use a `local` flag in the Compositor, which would create its Rasterio sources with a filename source instead of S3 source. It would also "list_objects" using the file structure instead of boto3; I think a utility function or two for that makes sense anyways, and adding a "local" flag to that utility function would enable our S3 Compositors to easily generalize the normal vs local modes.

I think what I'm proposing is similar to your second option, but less general. I think it will be easier to implement and easier to use.

**Comment by mpu-creare** [comment]
Maybe we could just have a file_open function in the datasource that handles paths that deal with s3://... just an idea.

**Comment by jmilloy** [comment]
With s3fs, it is even easier to generalize so that `s3://` paths and local paths are just two simple cases of the same node. I think s3fs is simple enough that if we need to implement those two cases in more than one place (e.g. `Rasterio`, `H5PY`, and `CSV`) that would be okay, even preferable, as each one may need to handle loading S3 data in slightly different ways.

**Comment by jmilloy** [comment]
I think we should also have a conversation about whether datasource `types` are based on the data *format* or the data *storage*. It is incongruous to me that we have format-based datasources such as `Rasterio` and `H5PY` alongside a storage-based datasources such as `S3`. Basically, I would remove the `S3` node.

Still thinking out loud. `Array` node and `Dataset` node are both clearly format-based. `PyDAP` and `WCS` are less clear but feel to me more like format-based nodes, as well. So `S3` is the odd one out.

I'm not sure about the `ReprojectedSource` node. It has always felt odd to me as a datasource. I guess it could be considered a format-based datasource whose format is a Node, but by that metric, all algorithm nodes are format-based datasource nodes whose format is a Node. I would choose to move the `ReprojectedSource` to `podpac/core/data/reprojection.py` or something like that.

**Comment by mpu-creare** [comment]
Yes, we do want to remove the `S3` datasource if we can just specify sources as `s3://` etc. I would much prefer that. 

`ReprojectedSource` has always been a little odd... it's really an algorithm node but it uses the `DataSource` machinery. Similarly, the `TimeInterpolationCompositor` (which we still have to write) is a compositor but uses `DataSource` machinery. I think there must be a better design pattern there somewhere...

**Comment by jmilloy** [comment]
@mpu-creare Can you tell me what an `s3://` source should look like? You could use the podpac-internal-test bucket and drought_parameters.zarr path as the example. Is `s3://podpac-internal-test/drought_parameters.zarr` sufficient (with the `AWS_REGION_NAME` setting for the region)?

**Comment by mpu-creare** [comment]
Yes, that should suffice. That matches what rasterio does, e.g: https://rasterio.readthedocs.io/en/stable/topics/switch.html?highlight=S3#dataset-identifiers  https://rasterio.readthedocs.io/en/stable/topics/vsi.html

**Comment by mlshapiro** [comment]
I completely agree that DataSource types should be *format* based. We all agree the S3 DataSource should be removed. 

I think the ReprojectedDataSource is really just a datasource with `DependentCoordinates`, so it would make sense to spec/improve the `DendentCoordinates` and remove `ReprojectedDataSource`, or if we want, have a `Reproject` algorithm.

The harder cases are `WCS` (or  `EGI` for that matter) which are DataSources, where storage and format start to mix (We assume that all the DataSource nodes have the data available and relatively quickly readable). As we grow more examples of these, perhaps we can extend the DataSource to support more complicated structures, but for now we should be pretty strict that DataSources are primarily *format* driven.

**Comment by mlshapiro** [comment]
I have to update TerrainTiles and will change to use s3fs

**Comment by jmilloy** [comment]
potentially prefer https://github.com/martindurant/filesystem_spec to s3fs

**Comment by mlshapiro** [comment]
@jmilloy is this solved by the S3Mixin? and if so, can we close this?

**Comment by jmilloy** [comment]
Yes, by a mix of the S3Mixin and the refactored/standardized file sources.
