### ISSUE TITLE
CoordinateGroup

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#2]
@mpu I think you know this, but there is an initial implementation with very basic tests in the repository. Here's a summary.

Both Coordinate and CoordinateGroup inherit from BaseCoordinate, which mainly just defines a common API (currently stack, unstack, and intersect).

The CoordinateGroup wraps a list of Coordinate objects in a private attribute. Maybe you would prefer that this be a numpy array, not sure.

**Implemented**
 - `len(group)`
 - `for c in group`
 - indexing `group[1]`
 - slicing `group[1:4]`
 - multi-indexing `group[1, 'lat']` to get the underlying Coord objects
 - `groupA + groupB`
 - `groupA += groupB`
 - `groupA.append(coordinate)`
 - `group.dims` gives a set of unstacked dims, shared by all coordinates in the group but not necessarily in the same order or stacking.
 - `group.stack`, `group.unstack`, and `group.intersect` just map to each coordinate in the list and return a CoordinateGroup.

**Not implemented**
 - `groupA + coordinate` - I didn't know if it was better to fail or to append.  
 - `add_unique`
 - `iterchunks`
 - `latlon_bounds_str`

**Next Steps**
 - initial feedback
 - how to execute a node given a CoordinateGroup and what the output should be

**Comment by jmilloy** [comment]
This issue is still outstanding.

The `CoordinatesGroup` will be used for native coordinates, so it will support indexing, intersection, and selection, but nodes will not be able to evaluate a node with a `CoordinatesGroup`. We may provide a convenience method or function for evaluating a node at each Coordinates in the group and returning a list of outputs.
