### ISSUE TITLE
Implement an HDF5-like container for cache

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#217]
**Description**
Right now the file cache stores data as a pickle. Pickle's can break across version of Python, and versions of the code. We want a more general solution. 

**Describe the solution you'd like**
Ideally our hdf5 file should follow the netcdf cf conventions, but perhaps that's too much to ask. The actual container doesn't HAVE to be hdf5 (zarr? geotiff? numpy's npz? something from xarray), but an appropriate, standard format is needed.

**Comment by mpu-creare** [comment]
I think for most xarray outputs we can just us the arr.to_netcdf() function, and then load using xarray as well. That should be pretty straightforward.

**Comment by jmilloy** [comment]
@drc @mpu-creare We cannot change the storage format of particular objects because we do not have "1 file = 1 hashed object". I think this was done to handle the (unlikely) case of clashing hash keys, and I think it is over-engineered. I have a few ideas about how to implement this, but I'm not sure if I should go ahead without discussing it with you guys. Maybe you have a better idea.

1. Simplify. Don't worry about non-unique hashes, and remove the `CacheListing` and the `CachePickleContainer` classes entirely. Then, just save/load each object using the desired format. I think this would take 2-4 hours to complete. I think this is preferable anyways. In the unlikely case that we need to deal with non-unique hashes in the future, we can implement that properly at that time.

2. Store 2 files per hash object: the object itself in the desired format along with a metadata file containing the JSON-serialized node, coordinates, and key (the `listing`). Again, we would remove the `CacheListing` and the `CachePickleContainer` classes. Non-unique hash keys would be resolved using the serialized metadata. I think this would take 4-8 hours to implement. I think it would also be simpler than the existing implementation and would be more flexible for future modifications.

3. Use one folder for each hash key, with 1 file for each object/listing that has that hash and a single metadata file containing the filenames for the listings in the folder. This would be the most direct modification. I would replace the `CachePickleContainer` with a `CacheFolderContainer`. I think this would take 4-6 hours. This would add complexity and testing to the existing implementation. I don't recommend this solution unless there is something about the other solutions that I've overlooked.

4. Something else that I'm missing?

**Comment by jmilloy** [comment]
The common idea for all of the above solutions is that there is a single file for each object that can be formated as desired given the type of the object. Maybe I am overlooking something about HDF5 that makes it easy to store multiple objects of various types in a dictionary using the "listing", or something like that.

**Comment by jmilloy** [comment]
@drc-creare and I are leaning towards option 2, noting that the metadata could alse be the most useful way to implement active cache management (e.g. storing last access time, number of accesses, etc) and maybe also to implement accessing partially cached results from overlapping regions. We're not going to implement either of those now, but that helpef tipped the scales in that direction.

@mpu-creare I'm going to get started on that tomorrow morning unless you jump in with a different opinion.

**Comment by mpu-creare** [comment]
It sounds like  you and @drc-creare came to a consensus. I like the metadata design, but we don't have to implement that right now. 

Incidentally, hdf5 let's you do almost anything you want. You could have multiple 'data' keys with multiple 'coordinates' keys, for example... so you could have 1 file for 2 objects with the same hash.

**Comment by mpu-creare** [comment]
Closed by #278
