### ISSUE TITLE
Updated Caching for 4.0 release, (including Smart Caching for data sources)

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#219]
**UPDATE**
We've been discussion caching in #498 and will continue the discussion here. 

**Required Use Cases for Caching**
* Speed up pipeline execution where nodes are re-used inside a pipeline for a single coordinates eval
* TODO: Add more

**Nice-to-Have Use Cases For Caching**
* Smart caching (as described below)
* TODO: add more

**Problems with Current Cache System**
* When debugging, caching should be turned off because the new/changed code often is not evaluated -- instead the cached values are. This can cause significant confusion driving the need for a global way to disable cache. 

**Description**

When a data source gets data from a remote file, we want to cache the data in such a way that an overlapping request will partially use the cached data, and partially download the additional data. 

Essentially, we want to minimize the data egress (ingress) at the expense of local storage and computational resources. 

**Describe the solution you'd like**

* Data from remote sources are cached so that the cached local file will have the same essential structure as the remote file (i.e. using the native coordinates)
    * Same geospatial coordinates, 
    * Same number of dimensions, 
    * etc. 
* The cached data files do not necessarily need to store all of the metadata and ancillary variables (we are not making and exact copy of the remote file. ) In fact, we might not even know the actual storage format of the remote file. 
* The caching here happens at the `get_data` method of DataSource coordinates (i.e. before ANY interpolation)
* Users need to be able to turn this on and off globally based on types of Nodes and specific instances of Nodes.
    * e.g. WHen I create a `SMAP` node I want to be able to say: 
        * Always cache the data to disk to minimize egress
        * OR, always use data from the remote source because I don't have lots of local storage. 
* NOTES: for the above, the writer of the SMAP node will have to implement mechanisms to allow instance-level control of caching.

**Comment by jmilloy** [comment]
I know this may not be high priority, but I'm interested in this. I wonder if we can break up large outputs into chunks of a specified shape for caching in order to support partial retrieval. Maybe I would add a `CACHE_COORDINATES_SHAPE` setting which would define static/consistent coordinate "tiles". Cache puts would break up the coordinates and corresponding data for storage, and cache gets would break up the requested coordinates, retrieve the data, and reassemble. Then the remaining missing data would be evaluated.

**Comment by mpu-creare** [comment]
I am also interested in this one, and I think it's now higher priority with the GeoWATCH server, and easier to do now that we have a better implementation/api for find_coordinates. We should discuss the specifics.

**Comment by CFoye-Creare** [comment]
new commit for this: a826efc

**Comment by CFoye-Creare** [comment]
See #498 for more detailed info.

**Comment by CFoye-Creare** [comment]
# Ideas and Progress

We have been able to implement `.cache()` and have made "CachingNode" work as a caching wrapper for nodes.

# Some things we can improve:

- [ ] Removal Policy for cache. (Time Limit for caching? Last Accessed?) We can use this when we run out of caching space.
- [ ] Custom hashes. We can create the option for Array nodes to use a custom hash instead of the JSON definition. We can also add more options for how to hash, etc.

**Comment by CFoye-Creare** [comment]
I Found an interesting description of a GIS cache, ESRI's "Compact Cache V2". https://github.com/Esri/raster-tiles-compactcache/blob/master/CompactCacheV2.md#why-compact-cache-v2

**Comment by CFoye-Creare** [comment]
GDAL's Update notes about their caching system: https://gdal.org/development/rfc/rfc26_blockcache.html

**Comment by CFoye-Creare** [comment]
# Ordered Compositor Framework
Implement this that the `CachingNode` *has* an `Ordered Compositor`, where the order of the nodes in the compositor is specified by the user, and the last node would be the datasource node.

- Replace the cache_stores with PODPAC nodes: RAM store with Array node (sparse arrays?)
- Replace File store with new `ZarrCache`
- Replace S3 store with new S3 path of `ZarrCache`

- By default, hash the `CachingNode` definition itself or allow for users to provide UUID to as a non-volatile hash in order to store the data
- Store data using `cache_path`, `default_s3_path`
- Writing occurs after you evaluate the compositor *if* it evals the datasource node. 
- This means we need to revise the `Ordered Compositor` to keep an attribute which node was successfully eval`ed.

**Comment by CFoye-Creare** [comment]
61fbebf3004949d400205902458f97a3519a6863

**Comment by mpu-creare** [comment]
see #507
