### ISSUE TITLE
Can't evaluate Node with Rotated Coordinates

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#363]
**Description**
See code below

**Steps to Reproduce**
```python
>>> import numpy as np
>>> from podpac.core.coordinates import Coordinates, RotatedCoordinates
>>> from podpac.data import Array
>>> rc = RotatedCoordinates(shape=(2, 4), theta=np.pi/8, origin=[10, 20], step=[-2.0, 1.0], dims=["lat", "lon"])
>>> c = Coordinates([rc])        
>>> node = Array(source=np.arange(8).reshape(2, 4),  native_coordinates=c)
>>> node.eval(c)
Traceback (most recent call last):
  Python Shell, prompt 10, line 1
    # Used internally for debug sandbox under external interpreter
  File "c:\Repositories\pipeline\podpac\podpac\core\node.py", line 860, in wrapper
    data = fn(self, coordinates, output=output)
  File "c:\Repositories\pipeline\podpac\podpac\core\data\datasource.py", line 358, in eval
    ) = self.native_coordinates.intersect(coordinates, outer=True, return_indices=True)
  File "c:\Repositories\pipeline\podpac\podpac\core\coordinates\coordinates.py", line 1065, in intersect
    return self.select(bounds, outer=outer, return_indices=return_indices)
  File "c:\Repositories\pipeline\podpac\podpac\core\coordinates\coordinates.py", line 1113, in select
    return self._make_selected_coordinates(selections, return_indices)
  File "c:\Repositories\pipeline\podpac\podpac\core\coordinates\coordinates.py", line 1120, in _make_selected_coordinates
    I = [e for l in I for e in l]
  File "c:\Repositories\pipeline\podpac\podpac\core\coordinates\coordinates.py", line 1120, in <listcomp>
    I = [e for l in I for e in l]
builtins.TypeError: 'slice' object is not iterable
```

**Expected Behavior**
This should return the data (1,2,3,4...) in a UnitsDataArray

**Additional Notes**
Full function from above traceback
```python
    def _make_selected_coordinates(self, selections, return_indices):
        if return_indices:
            coords = Coordinates([c for c, I in selections], **self.properties)
            # unbundle DepedentCoordinates indices
            I = [I if isinstance(c, DependentCoordinates) else [I] for c, I in selections]
            I = [e for l in I for e in l]  <-- fails here
            return coords, tuple(I)
        else:
            return Coordinates(selections, **self.properties)
```

**Comment by mpu-creare** [comment]
I marked a unittest `core.test.test_units.TestToGeoTiff.test_to_geotiff_roundtrip_rotcoords` as `xfail` till this is solved. This was on the feature/geotiff-export branch, 3833ad4

**Comment by jmilloy** [comment]
See also #280

**Comment by mpu-creare** [comment]
Ah! I missed #280. It's still a rare case, but let's try to take care of this for 2.0. Would be a nice capstone on the whole coordinates system.

**Comment by jmilloy** [comment]
There are several issues here

- [ ] evaluate an unstacked datasource node with rotated coordinates
- [ ] evaluate a rotated datasource with stacked, unstacked, shaped, and rotated coordinates
- [ ] rotated geotiff roundtrip

**Comment by jmilloy** [comment]
@mpu-creare Another option here would be *not* to support shaped datasources in general, and treat rotated coordinates as a special case. If a datasource has RotatedCoordinates source coordinates, we would unparameterize and flatten them so that the existing selection and interpolation machinery worked, and also save the rotated geotransform in order to support the geotiff roundtrip. What do yout think of that solution? That will be much easier to implement.

**Comment by mpu-creare** [comment]
I'm okay doing a special case for `RotatedCoordinates` especially if it's easy to support. I don't quite follow the implementation but I'd be happy to review the PR. 

We can leave the shaped datasources machinery in place without fully supporting them still... I'm also ok with that. It would be harder to take out that machinery and then put it back in once we need it.

**Comment by jmilloy** [comment]
@mpu-creare I'm having some additional issues with the RotatedCoordinates. I want to define the RotatedCoordinates using a `geotransform` (plus `shape`) insetad of `origin`, `theta`, and `step` (plus `shape`). From what I can see, rotated coordinates are about rotated geotiffs through rasterio, where the geotransform is fundamental. What do you think about that change? I can make a `RotatedCoordinates.from_parameters` classmethod that computes the geotransformation from an origin, theta, and step if that's still necessary as a user-friendly init method.

**Comment by jmilloy** [comment]
`ArrayCoordinates1d` with uniform coordinates are somewhat indistinguishable from an actual `UniformCoordinates1d` object
 * `start`, `stop`, `step`, `is_uniform`, and `coordinates` attributes
 * equal using `==`
 * `simplify` method returns a `UniformCoordinates1d` object

I need to define the same relationship for a rotated grid of `StackedCoordinates` and an actual `RotatedCoordinates` object
 * `geotransform`, `shape`, `is_rotated`, and `coordinates` attributes
 * equal using `==`
 * `simplify` method returns a `RotatedCoordinates` object

Another reason that the test in this issue is failing is because the `RotatedCoordinates` get transformed, which returns `StackedCoordinates`, and then the equality check fails. This would fix that twice over by fixing the equality check but also by returning `RotatedCoordinates` when possible. I'm going to do this tomorrow.

**Comment by jmilloy** [comment]
Made some progress on this. The AffineCoordinates are going to need work to handle different the cases correctly, but I'm going to push something that passes the geotiff roundtrip test as a starting point. Working on the interpolation now, where `source_data.sel(output_data.coords)` doesn't work with shaped stacked coordinates (affine or not).
