### ISSUE TITLE
The cache lock should be specific to a Node type. 

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#368]
**Description**
Right now two different nodes use the SAME cache lock. This leads to problems if, serially, both nodes need to check the cache. This can happen of Node1 checks has_cache, needs to compute it's sources for the source definition, which then needs to check the cache. 

This happened with the follow Code before 6e8c1f0a0a753b994dd5d4c75d0b041e089d04c0

**Steps to Reproduce**
```python
from podpac.datalib.terraintiles import TerrainTiles
from podpac import Coordinates, clinspace

# create terrain tiles node
node = TerrainTiles(tile_format='geotiff', zoom=8)

# create coordinates to get tiles
c = Coordinates([clinspace(40, 43, 1000), clinspace(-76, -72, 1000)], dims=['lat', 'lon'])

# evaluate node
o = node.eval(c)  # Locks when trying to get self.nan_vals because the cache is checked a second time
```

**Expected Behavior**
The reason for the lock in the first place is to ensure that two of the same Node don't try to simultaneously put something or retrieve something from the cache. This should NOT affect different Nodes. 

**Additional Notes**
Fix could be to implement a dictionary of locks within the thread manager that depends on the node definition, with a default global lock as a fallback... or perhaps the lock needs to happen deeper down in the caching machinery.

**Comment by mpu-creare** [comment]
@jmilloy  FYI... I see you've run into this too.

**Comment by mpu-creare** [comment]
Also related to #359

**Comment by jmilloy** [comment]
> Fix could be to implement a dictionary of locks within the thread manager that depends on the node definition

As a first reaction, I don't think this will work because the problem occurs when the node definition property tries to access the cache, so then we wouldn't be able to use the node definition to create the cache lock.

> This can happen of Node1 checks has_cache, needs to compute it's sources for the source definition, which then needs to check the cache.

Right. I think that *nothing* that is computed should be in the source definition, which fixes this issue, and is what #359 is about. 

Unfortunately, even with #359, a user *could* inadvertently do it wrong and cause themselves a head-ache. I think we could add machinery that raises an exception when a node definition tries to access the cache. It might be a bit complicated, but I think it would be isolated to the cache submodule.

**Comment by mpu-creare** [comment]
> As a first reaction, I don't think this will work because the problem occurs when the node definition property tries to access the cache, so then we wouldn't be able to use the node definition to create the cache lock.

Derp! That makes sense. And yes, I think #359 still makes this a lot better. 

I think we can just add a simple check that raises an exception to make things easier to debug. This check will only work on single-threaded execution, but would still reduce a lot of headache. 

Alternatively we can bury the lock further in the caching machinery, so that when the cache is ACTUALLY accessed, only then is it locked. That way everything that needs computing will already be computed, so this shouldn't occur... that's probably the right way to do it...

**Comment by mpu-creare** [comment]
@jmilloy just pinging you on this again. I believe we can close?

**Comment by jmilloy** [comment]
I'd have to really dig into this to figure this out. I suspect there are still some ways to cause the infinite loop (that we catch and raise an exception for) that would be fixed with the dictionary of locks. I think it's easy to implement and hard to test. I'm okay with closing this and revisiting if it becomes necessary at some point.

**Comment by mpu-creare** [comment]
Let's do that. This hasn't been a problem for quite a while now. We can always open a new issue when we have a real, testable use case. :)
