### ISSUE TITLE
Fix lat_lon order in Coordinate

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#42]
Its used to be ((lat_start, lon_start), (lat_end, lon_end), Number of points)
Now it's ((lat_start, lat_end), (lon_start, lon_end), Number of points)

**Comment by mlshapiro** [comment]
this may be a little off topic, but related to the tile.

Shoud `lat_lon` be input as a `list(tuple(lat, lon))` ie. `[(lat, lon), (lan, lon)]` - it seems like the list of points is not necessarily immutable on the client (though certainly it is immutable within podpac). 

This is related to clearly bounding the inputs to each method. Feel free ignore if this is perpendicular to the focus.

**Comment by jmilloy** [comment]
BTW `((lat_start, lon_start), (lat_end, lon_end), size)` makes a lot of sense... It would be a consistent `(start, stop, size)` for whether you're doing a single coordinate `lat` or stacked `lat_lon_time`.

As for `lat_lon` as an array, I would rather it accept an array in the shape (n, 2) -- like @mlshapiro has. I don't think we would need to force the argument to be a list of tuples, it could accept an array, a list of lists, a list of tuples, an array of tuples, whatever. But I would prefer that to a pair of lists or pair of arrays. Basically the same as above - more closely coupling the lat/lon pairs when stacked.

Thirdly, I don't really like how the stacked coordinates are stored as a structured array in the Coordinate object. It has really been frustrating to deal with, and I don't really see any benefits. It's related to the above because I would rather they were *also* an array of shape (n, 2).

Fourthly, I still suggest that we require Coordinate initialization to accept Coord objects, e.g. `Coordinate(lat_lon=(UniformCoord(...), UniformCoord(...)), time=Coord('2018-01-01'))` and handling the variety of user-friendly shortcuts in a separate method that is easy to document, test, and read. `unstack_dict` also muddles two separate tasks, and it would be simplified as well by this change. Maybe I'll throw together a pull request. I think it would simplify the user-facing aspects (usage, docs) of the Coordinate class and the internals (testing, actual implementation).

**Comment by mpu-creare** [comment]
I agree with all of the above. 1 small point: 
* I don't like the structured array either, it's cumbersome to work with
* The structured array is for xarray's benefit. This allows xarray to do all its magic seamlessly
* When I started this, xarray didn't have a mechanism to define a coordinate from two coordinates
    * I think that's no longer the case? I think they now have some sort of stacking as well? 
    * I think it would be better to use xarray's stacking mechanism... if it meets our needs

I do think what needs to happen is we need to write down a pretty clear spec. Something along the lines of: 
* I want to define this set of coordinates: This is the syntax

In fact, that turns into a unittest pretty easily. 

As far as where the user-friendly shortcuts live, I don't care that much. I picked the Coordinate constructor, but if people don't like it I'm find having it live elsewhere.

**Comment by jmilloy** [comment]
Can you point out briefly, maybe in a few lines or maybe a link to somewhere in the code here, how the structured array is used by xarray in a special way? I think that would be helpful for me.

**Comment by mpu-creare** [comment]
I.e. automatically adding two non-overlapping dataarrays

```python
>>> import podpac
>>> node1 = podpac.Node(native_coordinates=podpac.Coordinate(lat_lon=((1, 2), (3, 4), 5)))
>>> node2 = podpac.Node(native_coordinates=podpac.Coordinate(lat_lon=((1.5, 2.5), (3.5, 4.5), 5)))
>>> node1.output + node2.output
<xarray.UnitsDataArray (lat_lon: 3)>
array([nan, nan, nan])
Coordinates:
  * lat_lon  (lat_lon) object (1.5, 3.5) (1.75, 3.75) (2.0, 4.0)
```

I thought it worked with re-index, but apparently not...

**Comment by jmilloy** [comment]
I finally fully wrapped my head around the Coordinate class. Merge request coming at some point soon with some good docs following shortly behind.

**Comment by jmilloy** [comment]
Unfortunately, there is a good reason to do `lat_lon=([lat1, lat2, ..., latN], [lon1, lon2, ..., lonN])` as opposed to `lat_lon=[[lat1, lon1], [lat2, lon2], ..., [latN, lonN]]`. You way wish to do `lat_lon`=([lat1, lat2, ..., latN], (lon1, lonN, N)`.

**Comment by mpu-creare** [comment]
I think this discussion is superseded by  #54. Closing.
