### ISSUE TITLE
Improve WCS client support

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#423]
**Description**
The current WCS client is custom and not full features

**Describe the solution you'd like**
Use an external library such as `rasterio` or `owslib` and create a light-weight Node wrapper around this library. This would also allow our node to explore the available layers and CRS supported by the other server.

**Sample Code**
```
>>> wcs = podpac.data.WCS(source=server_url)
>>> wcs.available_layers
['a', 'b', ...]
>>> wcs.available_crs
['epsg:4326', ...]
>>> wcs_a = podpac.data.WCS(source=server_url, layer = wcs.available_layers[0])  # if the user knows the layer name, the above lines are not needed. 
```

**Comment by jmilloy** [comment]
@mpu-creare I see how to use owslib as a WCS client, possibly *with rasterio*, but not how to use rasterio alone. Can you point me to a resource for rasterio? Or shall I just go ahead with owslib?

**Comment by mpu-creare** [comment]
Just go ahead with owslib. The main point is that we don't write our own fragile client.

**Comment by jmilloy** [comment]
Do you know of a source that the existing WCS datasource works with? It would be useful for comparison.

**Comment by jmilloy** [comment]
If you evaluate a WCS node with **uniform unstacked coordinates (a grid)**, it's trivial to translate that into a bounding box and shape for the GetCoverage request. The interpolation happens on the WCS server. This is really nice because avoids the high-resolution of the WCS source grid.

If you evaluate a WCS node with **non-uniform or stacked coordinates**, we could make a request for every point, which would use the interpolation on the WCS server and return data consistent with the gridded requests, but that is simply too slow. So the other option is to make larger gridded request(s) and then interpolate within podpac. This will give slightly inconsistent results for the same coordinate if it is part of a grid in one case (using WCS interpolation) or part of a stacked coordinates list in another (using podpac interpolation). @mpu-creare is that okay?

Should I just not worry about that slight inconsistency, or should I go back to also using podpac interpolation for uniform grid coordinates, too?

**Comment by mpu-creare** [comment]
Don't worry about the inconsistency.  

We probably should talk about the interpolation and selectors at some point today...

**Comment by jmilloy** [comment]
How about a WCS server with time that I can test with?
