### ISSUE TITLE
Verbify Compositor --> Composite

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#427]
Mark for depreciation, in version 3.0 (for removal in version 4.0).  

Noun | Verb
---- | ----
**Compositor** | Composite
Reprojector | **Reproject**
Interpolator | **Interpolate**
CoordinatesModifier | **ModifyCoordinates**
CoordinatesExpander | **ExpandCoordinates**
CoordinatesSelector | **SelectCoordinates**
Combiner | **Combine**
**Convolution** | Convolve
ReductionOperator | **Reduce**

*(current name in **bold**)*

**Comment by jmilloy** [comment]
The essense of this issue is to be consistent. I know I originally proposed the verb, but now I've changed my mind. There is some consensus that class names should not be verbs: the *methods* are the verbs. 

Noun | Verb
---- | ----
**Compositor** | Composite
Reprojector | **Reproject**
Interpolator | **Interpolate**
CoordinatesModifier | **ModifyCoordinates**
CoordinatesExpander* | **ExpandCoordinates**
CoordinatesSelector | **SelectCoordinates**
Combiner** | **Combine**
**Convolution** | Convolve
ReductionOperator | **Reduce**

*(current name in **bold**)*

 *CoordinatesEntender? CoordinatesPadding?
**Aggregator? Collector?

**Comment by jmilloy** [comment]
See, for example, pyproj transformers:

```
transformer = pyproj.Transformer(...)
newcoords = transformer.transform(...)
```

**Comment by mpu-creare** [comment]
Wow! Went the other way. I didn't expect that., but yes, that makes sense. Ok. Let's plan to go with Nouns. 

I like `Expander`

**Comment by jmilloy** [comment]
The API naming and structure needs a full audit.

**Comment by jmilloy** [comment]
I suspect we won't make any significant changes at this point, but in any case this has been superseded by #439
