### ISSUE TITLE
[bug] Dependency on dummy version of osgeo

### ISSUE THREAD

**Issue by isabellasoldner** [creare-com/podpac#483]
**Description**
Podpac has a dependency on a dummy version of osgeo due to pip install osgeo, which does not install osgeo. 
See dummy version here: 
https://pypi.org/project/osgeo/

We noticed this when we upgraded podpac to the latest version.

**Observed Behavior**
We noticed this as we installed package dependent on podpac in our docker container and it failed to build due to the dummy package.
![Screenshot from 2021-06-04 13-07-11](https://user-images.githubusercontent.com/27289127/120798796-cab91d80-c535-11eb-9dda-11d3227de835.png)

**Comment by mpu-creare** [comment]
How are you installing podpac? It looks like you're using a requirements.txt file?

**Comment by isabellasoldner** [comment]
Just a setup.py file
Minimum example:
setup(
            name="repo-name",
            version="v1.6.2",
            packages=find_packages(),
            install_requires=[podpac[all]>=2.2.1])

**Comment by ketozhang** [comment]
Same issue, it's a osgeo is a dependency of podpac==3.1.0 and maybe >=3

**Comment by jmilloy** [comment]
I don't see `osgeo` specified as a requirement in the podpac setup.py file.

The `osgeo` module is required for the new `OGR` datasource, and indeed it is found in the `gdal` package instead of the dummy `osgeo` package. I didn't include `gdal` in the podpac setup.py requirements because it can be a headache, and I definitely didn't include the dummy `osgeo` package.

It seems like somehow `osgeo` ends up in your requirements.txt file, even though it shouldn't. Can either of you be more specific about how you are installing podpac? At what point do you create and/or use a requirements.txt file, and can you post that file?

**Comment by jmilloy** [comment]
I can confirm that simply install podpac using `pip install podpac[all]` causes this error.

Note that installing from the local repository with `pip install .[all]` works just fine.

**Comment by mpu-creare** [comment]
I figured it out. I'll push a 3.1.1 later this afternoon. 

I had a local change in my setup.py file when I uploaded it to PyPi... was testing something for someone...

**Comment by mpu-creare** [comment]
Okay, I just pushed 3.1.1 up to PyPI. Please let me know if that fixes your problem.

**Comment by isabellasoldner** [comment]
Seems to work now, yes

**Comment by mpu-creare** [comment]
Great! Sorry for the initial mistake.
