### ISSUE TITLE
Set up Maintainable AWS infrastructure

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#85]
**Description**
We need a mechanism to update our podpac lambda function implementation for the different releases

**Describe the solution you'd like**
Get our AWS infrastructure in place. -- Use a docker image? User  a script? Use the awscli? User a 3rd party library to do things? 

* Need to manage:
    * A lambda function installation with a RestFUL API
    * An EC 2 instance that can be cloned and run a Jupyterlab demo server

**Additional context**
* Ideally we should have instructions/script/documentation so that others (external folks) can recreate these lambda functions from scratch
* We should also make some of these public so other folks can import/clone our installations

**Comment by dsully1992** [comment]
So far, I've created a DockerFile in the `dist/aws` directory, which installs `podpac` and its dependencies on a base container distributed by amazon. This container replicates the ec2 instance used by Lambda functions, which makes this approach pretty useful. I think this approach is our best option, since it can be used to create both Lambda functions and EC2 instances.

**Comment by dsully1992** [comment]
@mpu-creare Do nodes/coordinates already store the information needed for the node JSON we're using to execute in Lambda functions? I see node definitions include the 'pipeline' property, but am unsure how to get the output and coordinates properties. The coordinates object might not have everything the JSON object is expected to have. For an example, see example.json in feature/aws. This is the JSON for a SinCoords node.

**Comment by mpu-creare** [comment]
You bring up a good point. Traditionally the lambda function worked off the WCS payload to determine coordinates (uniform), but with PODPAC we could ask the Coordinates node to create WCS coordinates, or output our own JSON that makes sense (i.e. more full-featured). 

@jmilloy Any thoughts.

**Comment by dsully1992** [comment]
@jmilloy @mpu-creare I had deleted the comment above with plans to take the conversation offline. 

Instead, we can discuss this here. Since this comment, I added a property to `Output`, which is only implemented for `ImageOutput` as of now. This property is the output definition, like this:

```json
{
  "pipeline": {
    "nodes": {
      "SinCoords": {
        "node": "core.algorithm.algorithm.SinCoords",
        "inputs": {}
      }
    }
  },
  "output": [{
    "mode": "image",
    "format": "png",
    "vmin": -1.2,
    "vmax": 1.2,
    "nodes": [
      "SinCoords"
    ]
  }],
  "coordinates":
  {
    "TIME": "2018-03-03",
    "BBOX": "-180.0,-90.0,180.0,90.0",
    "WIDTH": 256,
    "HEIGHT": 256
  }
}
```

My thought is to do something similar - or a `to_json`/`make_pipeline_definition` for coordinates. As long as I can get those fields from coordinates, I'm happy. Node and Output return these in an `OrderedDict`, which I think makes sense for `Coordinates` as well.

**Comment by dsully1992** [comment]
An alternative is to separately parameterize these fields in `aws_lambda` so users have to explicitly provide them in order to execute the node on AWS.

**Comment by jmilloy** [comment]
Oh, that output. Okay. I think the output should be part of the pipeline definition. At least, pipeline's support an output:

```
{
  "pipeline": {
    "nodes": {
      "SinCoords": {
        "node": "core.algorithm.algorithm.SinCoords",
        "inputs": {}
      }
    },
    "output": {
      "mode": "image",
      "format": "png",
      "vmin": -1.2,
      "vmax": 1.2,
      "node": "SinCoords"
    }
  },
  "coordinates":
  {
    "TIME": "2018-03-03",
    "BBOX": "-180.0,-90.0,180.0,90.0",
    "WIDTH": 256,
    "HEIGHT": 256
  }
}
```
