### ISSUE TITLE
Don't Save Username and Password in JSON pipeline definition

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#94]
**Description**
Currently SMAP nodes save the username and password in the JSON. These are tagged attributes. 

**Steps to Reproduce**
See `SMAP-level4-data-access.ipynb`

**Expected Behavior**
username and password should not be saved.

**Comment by jmilloy** [comment]
Currently, the pipeline parser doesn't check whether the attrs you are setting are tagged as `attr=True`. I don't think that's a problem, and it means that you can remove the attr tag from these traits so that they won't be automatically included in the pipeline definition, still assign them in pipelines, and then handle outputting a placeholder in the definition in the SMAP nodes.

**Comment by mpu-creare** [comment]
This was fixed, missed which commit it happened in. Likely during the SMAP robustness updates recently .
